apiVersion: apps/v1
kind: Deployment
metadata:
  name: tebofy-api
  namespace: default
  labels:
    app: tebofy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tebofy-api
  template:
    metadata:
      labels:
        app: tebofy-api
    spec:
      containers:
      - name: tebofy-api
        image: registry.gitlab.com/tebofy/tebofy-web-api:0f65436ad5b1163f85d998839a7818f4f40b123b
        imagePullPolicy: Always
        ports:
        - containerPort: 3400
          name: web
          protocol: TCP
      imagePullSecrets:
      - name: gitlab-auth

---

# ------------------- Service ------------------- #
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: tebofy-api
  name: tebofy-api
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 3400
    targetPort: 3400
  selector:
    app: tebofy-api
  type: LoadBalancer