apiVersion: apps/v1
kind: Deployment
metadata:
  name: tebofy-api
  namespace: default
  labels:
    app: tebofy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tebofy-api
  template:
    metadata:
      labels:
        app: tebofy-api
    spec:
      containers:
      - name: tebofy-api
        image: registry.gitlab.com/tebofy/tebofy-web-api:e2021ccf7b106a225478702e0f12a0cebaa5c267
        imagePullPolicy: Always
        ports:
        - containerPort: 3400
          name: web
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/health-check
            port: 3400
          failureThreshold: 1
          periodSeconds: 10
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /api/health-check
            port: 3400
          failureThreshold: 1
          periodSeconds: 10
          initialDelaySeconds: 120
      imagePullSecrets:
      - name: gitlab-auth

---

# ------------------- Service ------------------- #
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: tebofy-api
  name: tebofy-api
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 3400
    targetPort: 3400
  selector:
    app: tebofy-api

# --- Cron -- #

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tebofy-api-my-daily-cron
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tebofy-api-my-daily-cron-container
            image: appropriate/curl
            env:
            - name: URL
              value: "http://tebofy-api:3400/task/push-my-daily-notification"
            - name: XTOKEN
              value: "GbPEL66WcfkE4gn9jCHpaffK2DTdkT9R"
            args: ["-vk", "-H", "x-token: $(XTOKEN)", "$(URL)"]
          restartPolicy: OnFailure
