{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nodeapp.serviceAccountName" . }}
  labels:
{{ include "nodeapp.labels" . | indent 4 }}
{{- end -}}
